import { dayNumber, letterCount } from './util.js';
import { ROTATION, ROTATION_EPOCH } from './rotation.js';
import { LOCALE } from './locale.js';

// This bank is Swedish, and so is the rotation that orders it. Every other
// language-bound piece has moved under locales/, but the bank has not yet —
// authoring one is the slow part, not the plumbing.
//
// Until it does, refuse to start rather than serve Swedish words to a player
// reading English rules. That failure would look like a broken game; this looks
// like the missing step it is.
if (LOCALE.code !== 'sv') {
  throw new Error(
    `No word bank for locale "${LOCALE.code}". The bank and its rotation are still `
    + 'Swedish-only — see server/locales/ for the pieces that have moved. '
    + 'Set ORDKNAPP_LOCALE=sv, or author server/locales/'
    + `${LOCALE.code}/words.js and its rotation first.`,
  );
}

// Hand-authored word bank. Writing the forbidden lists is the Taboo craft —
// each list blocks the five most obvious clue routes for its word.
//
// The bank is weighted toward 5–6-letter words (the difficulty sweet spot:
// difficulty is neighbourhood density — how many real same-length words live
// near the concept). Targets are 3–9 letters; every entry carries exactly five
// forbidden words, none identical to the target. Those invariants are enforced
// by the tests, so new batches can be pasted in and validated by `npm test`.
//
// Authored in themed batches (natur · hem & mat · samhälle & teknik · kultur &
// kropp · verb · adjektiv) and stored in that order, so the array is grouped by
// theme. The daily rotation does not walk the array in order — it strides
// across it (see wordForDate) precisely so consecutive days don't come from the
// same batch.
//
// Most entries are nouns and carry no `class` in the table below; wordByIndex
// fills in 'substantiv'. Verbs and adjectives say so explicitly. Either way the
// class is shown to the player and passed to the guesser alongside the letter
// count.
//
// Telling the guesser matters: without it, a mostly-noun bank teaches the model
// to answer with nouns, and every verb and adjective would be harder for a
// reason that has nothing to do with the player's clue. It gives nothing away
// either, since the player can see the word class on their own screen.
export const WORDS = [
  { word: 'morot', forbidden: ['grönsak', 'orange', 'kanin', 'rot', 'odla'] },
  { word: 'sommar', forbidden: ['årstid', 'sol', 'varm', 'semester', 'vinter'] },
  { word: 'strand', forbidden: ['sand', 'hav', 'bad', 'sol', 'semester'] },
  { word: 'äpple', forbidden: ['frukt', 'träd', 'rött', 'äta', 'paj'] },
  { word: 'fågel', forbidden: ['flyga', 'vinge', 'näbb', 'djur', 'kvittra'] },
  { word: 'skola', forbidden: ['elev', 'lärare', 'klass', 'lektion', 'undervisning'] },
  { word: 'vinter', forbidden: ['kall', 'snö', 'årstid', 'jul', 'is'] },
  { word: 'cykel', forbidden: ['hjul', 'trampa', 'åka', 'fordon', 'styre'] },
  { word: 'lampa', forbidden: ['ljus', 'lysa', 'tak', 'tända', 'el'] },
  { word: 'stjärna', forbidden: ['himmel', 'natt', 'lysa', 'kändis', 'rymden'] },
  { word: 'hjärta', forbidden: ['kärlek', 'pumpa', 'blod', 'organ', 'slå'] },
  { word: 'pengar', forbidden: ['betala', 'mynt', 'sedel', 'rik', 'valuta'] },
  { word: 'kaffe', forbidden: ['dryck', 'dricka', 'böna', 'kopp', 'koffein'] },
  { word: 'spegel', forbidden: ['glas', 'reflektera', 'bild', 'badrum', 'se'] },
  { word: 'nyckel', forbidden: ['lås', 'dörr', 'öppna', 'knippa', 'hänglås'] },
  { word: 'telefon', forbidden: ['ringa', 'samtal', 'mobil', 'prata', 'nummer'] },
  { word: 'blomma', forbidden: ['växt', 'doft', 'kronblad', 'vas', 'trädgård'] },
  { word: 'gitarr', forbidden: ['sträng', 'spela', 'musik', 'instrument', 'ackord'] },
  { word: 'soffa', forbidden: ['sitta', 'möbel', 'vardagsrum', 'ligga', 'kudde'] },
  { word: 'glass', forbidden: ['kall', 'äta', 'strut', 'sommar', 'smak'] },
  { word: 'regn', forbidden: ['väder', 'vatten', 'paraply', 'blöt', 'moln'] },
  { word: 'hund', forbidden: ['djur', 'skälla', 'koppel', 'husdjur', 'valp'] },
  { word: 'klocka', forbidden: ['tid', 'visare', 'armband', 'ringa', 'timme'] },
  { word: 'fönster', forbidden: ['glas', 'öppna', 'hus', 'utsikt', 'karm'] },
  { word: 'kudde', forbidden: ['sova', 'säng', 'mjuk', 'huvud', 'fjäder'] },
  { word: 'banan', forbidden: ['frukt', 'gul', 'skal', 'apa', 'böjd'] },
  { word: 'socker', forbidden: ['söt', 'baka', 'vit', 'bit', 'kaffe'] },
  { word: 'vante', forbidden: ['hand', 'vinter', 'kall', 'sticka', 'par'] },
  { word: 'brasa', forbidden: ['eld', 'ved', 'värme', 'spis', 'mysig'] },
  { word: 'hylla', forbidden: ['bok', 'vägg', 'förvara', 'plank', 'ställa'] },
  { word: 'öken', forbidden: ['sand', 'torr', 'varm', 'kamel', 'sahara'] },
  { word: 'sjukhus', forbidden: ['läkare', 'vård', 'patient', 'sjuk', 'operation'] },
  { word: 'piano', forbidden: ['tangent', 'spela', 'musik', 'instrument', 'flygel'] },
  { word: 'raket', forbidden: ['rymd', 'flyga', 'nyår', 'fart', 'uppskjutning'] },
  { word: 'segel', forbidden: ['båt', 'vind', 'mast', 'hav', 'duk'] },
  { word: 'krona', forbidden: ['kung', 'huvud', 'pengar', 'valuta', 'guld'] },
  { word: 'dimma', forbidden: ['sikt', 'grå', 'väder', 'moln', 'morgon'] },
  { word: 'kamera', forbidden: ['foto', 'bild', 'lins', 'filma', 'knäppa'] },
  { word: 'tavla', forbidden: ['konst', 'vägg', 'måla', 'ram', 'klassrum'] },
  { word: 'boll', forbidden: ['rund', 'kasta', 'spela', 'studsa', 'fotboll'] },
  { word: 'björk', forbidden: ['träd', 'vit', 'näver', 'löv', 'skog'] },
  { word: 'björn', forbidden: ['djur', 'skog', 'ide', 'honung', 'stor'] },
  { word: 'ekorre', forbidden: ['djur', 'nöt', 'svans', 'träd', 'hoppa'] },
  { word: 'groda', forbidden: ['hoppa', 'grön', 'damm', 'kväka', 'padda'] },
  { word: 'fjäril', forbidden: ['insekt', 'vinge', 'larv', 'blomma', 'flyga'] },
  { word: 'geting', forbidden: ['insekt', 'stick', 'gul', 'randig', 'bo'] },
  { word: 'snigel', forbidden: ['långsam', 'slem', 'skal', 'trädgård', 'krypa'] },
  { word: 'humla', forbidden: ['insekt', 'surra', 'blomma', 'gul', 'bi'] },
  { word: 'mygga', forbidden: ['insekt', 'stick', 'kliar', 'sommar', 'surra'] },
  { word: 'gädda', forbidden: ['fisk', 'sjö', 'tänder', 'meta', 'rovdjur'] },
  { word: 'krabba', forbidden: ['hav', 'klo', 'skal', 'strand', 'sidled'] },
  { word: 'mussla', forbidden: ['skal', 'hav', 'sand', 'öppna', 'äta'] },
  { word: 'snäcka', forbidden: ['skal', 'strand', 'hav', 'spiral', 'lyssna'] },
  { word: 'kråka', forbidden: ['fågel', 'svart', 'kraxa', 'flyga', 'näbb'] },
  { word: 'uggla', forbidden: ['fågel', 'natt', 'ögon', 'träd', 'vis'] },
  { word: 'svala', forbidden: ['fågel', 'flyga', 'sommar', 'bo', 'flytta'] },
  { word: 'rådjur', forbidden: ['skog', 'hjort', 'bambi', 'hoppa', 'vilt'] },
  { word: 'kanin', forbidden: ['öron', 'hoppa', 'morot', 'bur', 'hare'] },
  { word: 'bäver', forbidden: ['damm', 'gnaga', 'träd', 'vatten', 'svans'] },
  { word: 'lodjur', forbidden: ['katt', 'vild', 'skog', 'tofs', 'rovdjur'] },
  { word: 'fjäder', forbidden: ['fågel', 'lätt', 'vinge', 'kudde', 'flyga'] },
  { word: 'vinge', forbidden: ['fågel', 'flyga', 'flygplan', 'fjäril', 'luft'] },
  { word: 'storm', forbidden: ['vind', 'hård', 'väder', 'blåsa', 'träd'] },
  { word: 'hagel', forbidden: ['is', 'himmel', 'falla', 'korn', 'väder'] },
  { word: 'himmel', forbidden: ['blå', 'moln', 'uppe', 'sol', 'luft'] },
  { word: 'skugga', forbidden: ['sol', 'mörk', 'ljus', 'träd', 'svalt'] },
  { word: 'grotta', forbidden: ['berg', 'mörk', 'hål', 'sten', 'inne'] },
  { word: 'vulkan', forbidden: ['berg', 'lava', 'utbrott', 'eld', 'aska'] },
  { word: 'vatten', forbidden: ['dricka', 'våt', 'hav', 'flytande', 'genomskinlig'] },
  { word: 'källa', forbidden: ['vatten', 'mark', 'rinna', 'dricka', 'ren'] },
  { word: 'svamp', forbidden: ['skog', 'plocka', 'hatt', 'giftig', 'korg'] },
  { word: 'mossa', forbidden: ['grön', 'skog', 'mjuk', 'sten', 'växa'] },
  { word: 'kotte', forbidden: ['gran', 'tall', 'skog', 'frö', 'kasta'] },
  { word: 'buske', forbidden: ['växt', 'liten', 'träd', 'grön', 'trädgård'] },
  { word: 'kaktus', forbidden: ['tagg', 'öken', 'växt', 'kruka', 'torr'] },
  { word: 'tulpan', forbidden: ['blomma', 'vår', 'lök', 'vas', 'holland'] },
  { word: 'hallon', forbidden: ['bär', 'röd', 'buske', 'söt', 'sylt'] },
  { word: 'blåbär', forbidden: ['bär', 'blå', 'skog', 'plocka', 'ris'] },
  { word: 'klippa', forbidden: ['sten', 'berg', 'brant', 'hav', 'hög'] },
  { word: 'fjord', forbidden: ['norge', 'hav', 'vik', 'berg', 'smal'] },
  { word: 'kulle', forbidden: ['hög', 'backe', 'berg', 'liten', 'gräs'] },
  { word: 'träsk', forbidden: ['blöt', 'mark', 'sank', 'vatten', 'kärr'] },
  { word: 'lavin', forbidden: ['snö', 'berg', 'rasa', 'fjäll', 'farlig'] },
  { word: 'klöver', forbidden: ['gräs', 'fyra', 'blad', 'tur', 'äng'] },
  { word: 'nässla', forbidden: ['bränna', 'grön', 'ogräs', 'soppa', 'kliar'] },
  { word: 'tistel', forbidden: ['tagg', 'ogräs', 'lila', 'blomma', 'sticka'] },
  { word: 'lilja', forbidden: ['blomma', 'vit', 'vas', 'doft', 'trädgård'] },
  { word: 'syren', forbidden: ['buske', 'lila', 'doft', 'vår', 'blomma'] },
  { word: 'stubbe', forbidden: ['träd', 'hugga', 'skog', 'sitta', 'kvar'] },
  { word: 'kvist', forbidden: ['gren', 'träd', 'liten', 'knäcka', 'torr'] },
  { word: 'knopp', forbidden: ['blomma', 'vår', 'spricka', 'gren', 'liten'] },
  { word: 'honung', forbidden: ['bi', 'söt', 'kupa', 'klibbig', 'gul'] },
  { word: 'granit', forbidden: ['sten', 'hård', 'berg', 'grå', 'bergart'] },
  { word: 'silver', forbidden: ['metall', 'vit', 'smycke', 'dyr', 'blank'] },
  { word: 'marmor', forbidden: ['sten', 'vit', 'staty', 'ådra', 'hård'] },
  { word: 'pärla', forbidden: ['mussla', 'vit', 'halsband', 'rund', 'dyr'] },
  { word: 'hummer', forbidden: ['hav', 'klo', 'skal', 'röd', 'äta'] },
  { word: 'korall', forbidden: ['hav', 'rev', 'färg', 'växa', 'dykare'] },
  { word: 'manet', forbidden: ['hav', 'bränna', 'geggig', 'simma', 'genomskinlig'] },
  { word: 'torsk', forbidden: ['fisk', 'hav', 'äta', 'filé', 'fånga'] },
  { word: 'orkan', forbidden: ['vind', 'storm', 'väder', 'kraftig', 'förstöra'] },
  { word: 'istapp', forbidden: ['is', 'tak', 'hänga', 'vinter', 'spetsig'] },
  { word: 'blixt', forbidden: ['åska', 'ljus', 'himmel', 'snabb', 'slå'] },
  { word: 'delfin', forbidden: ['hav', 'simma', 'smart', 'hoppa', 'däggdjur'] },
  { word: 'tiger', forbidden: ['randig', 'katt', 'djungel', 'rovdjur', 'orange'] },
  { word: 'lejon', forbidden: ['man', 'kung', 'savann', 'ryta', 'katt'] },
  { word: 'giraff', forbidden: ['hals', 'lång', 'prickig', 'afrika', 'djur'] },
  { word: 'magma', forbidden: ['lava', 'vulkan', 'het', 'smält', 'berg'] },
  { word: 'abborre', forbidden: ['fisk', 'sjö', 'randig', 'meta', 'fena'] },
  { word: 'gröda', forbidden: ['åker', 'skörd', 'växa', 'bonde', 'säd'] },
  { word: 'havre', forbidden: ['gryn', 'säd', 'gröt', 'åker', 'korn'] },
  { word: 'hassel', forbidden: ['nöt', 'buske', 'skal', 'brun', 'ekorre'] },
  { word: 'valnöt', forbidden: ['skal', 'knäcka', 'brun', 'äta', 'träd'] },
  { word: 'struts', forbidden: ['fågel', 'stor', 'ägg', 'springa', 'hals'] },
  { word: 'panda', forbidden: ['svart', 'vit', 'bambu', 'björn', 'kina'] },
  { word: 'kruka', forbidden: ['blomma', 'lera', 'jord', 'fönster', 'planta'] },
  { word: 'igelkott', forbidden: ['tagg', 'liten', 'boll', 'djur', 'sova'] },
  { word: 'spindel', forbidden: ['nät', 'ben', 'insekt', 'krypa', 'fluga'] },
  { word: 'pingvin', forbidden: ['is', 'svart', 'vit', 'simma', 'fågel'] },
  { word: 'elefant', forbidden: ['snabel', 'stor', 'grå', 'bete', 'afrika'] },
  { word: 'glaciär', forbidden: ['is', 'berg', 'smälta', 'kall', 'långsam'] },
  { word: 'regnbåge', forbidden: ['färg', 'regn', 'sol', 'himmel', 'båge'] },
  { word: 'gryning', forbidden: ['morgon', 'sol', 'ljus', 'tidig', 'natt'] },
  { word: 'älg', forbidden: ['skog', 'horn', 'stor', 'jakt', 'djur'] },
  { word: 'räv', forbidden: ['röd', 'svans', 'listig', 'skog', 'djur'] },
  { word: 'varg', forbidden: ['yla', 'flock', 'skog', 'hund', 'rovdjur'] },
  { word: 'hav', forbidden: ['vatten', 'salt', 'båt', 'våg', 'blå'] },
  { word: 'snö', forbidden: ['vit', 'kall', 'vinter', 'flinga', 'smälta'] },
  { word: 'moln', forbidden: ['himmel', 'vit', 'luft', 'flyta', 'grå'] },
  { word: 'åska', forbidden: ['blixt', 'dunder', 'moln', 'ljud', 'mullra'] },
  { word: 'skog', forbidden: ['träd', 'gran', 'mörk', 'svamp', 'vandra'] },
  { word: 'berg', forbidden: ['hög', 'sten', 'klättra', 'topp', 'fjäll'] },
  { word: 'sten', forbidden: ['hård', 'berg', 'tung', 'kasta', 'grå'] },
  { word: 'sand', forbidden: ['korn', 'öken', 'gul', 'gräva', 'hink'] },
  { word: 'jord', forbidden: ['mark', 'brun', 'gräva', 'planta', 'planet'] },
  { word: 'gräs', forbidden: ['grön', 'klippa', 'mark', 'sommar', 'matta'] },
  { word: 'löv', forbidden: ['träd', 'höst', 'grön', 'falla', 'kratta'] },
  { word: 'höst', forbidden: ['löv', 'årstid', 'regn', 'kall', 'skörd'] },
  { word: 'guld', forbidden: ['metall', 'gul', 'dyr', 'ring', 'skatt'] },
  { word: 'gaffel', forbidden: ['bestick', 'äta', 'tandad', 'kniv', 'mat'] },
  { word: 'gryta', forbidden: ['kastrull', 'koka', 'mat', 'spis', 'lock'] },
  { word: 'panna', forbidden: ['steka', 'spis', 'handtag', 'kök', 'järn'] },
  { word: 'mjölk', forbidden: ['ko', 'vit', 'dricka', 'glas', 'mejeri'] },
  { word: 'grädde', forbidden: ['mjölk', 'vispa', 'tårta', 'fet', 'vit'] },
  { word: 'peppar', forbidden: ['salt', 'krydda', 'svart', 'kvarn', 'nysa'] },
  { word: 'kanel', forbidden: ['bulle', 'krydda', 'brun', 'gröt', 'pulver'] },
  { word: 'gurka', forbidden: ['grön', 'grönsak', 'sallad', 'lång', 'inlagd'] },
  { word: 'tomat', forbidden: ['röd', 'grönsak', 'ketchup', 'sallad', 'frukt'] },
  { word: 'sallad', forbidden: ['grön', 'grönsak', 'blad', 'skål', 'dressing'] },
  { word: 'päron', forbidden: ['frukt', 'grön', 'träd', 'söt', 'saftig'] },
  { word: 'citron', forbidden: ['gul', 'sur', 'frukt', 'juice', 'skiva'] },
  { word: 'druva', forbidden: ['vin', 'klase', 'frukt', 'grön', 'russin'] },
  { word: 'russin', forbidden: ['druva', 'torkad', 'söt', 'kaka', 'skrynklig'] },
  { word: 'våffla', forbidden: ['järn', 'grädde', 'sylt', 'rutig', 'smet'] },
  { word: 'semla', forbidden: ['bulle', 'grädde', 'mandelmassa', 'fastlag', 'fika'] },
  { word: 'macka', forbidden: ['bröd', 'smör', 'ost', 'smörgås', 'skiva'] },
  { word: 'pasta', forbidden: ['spagetti', 'italiensk', 'koka', 'sås', 'nudel'] },
  { word: 'tröja', forbidden: ['kläder', 'ull', 'varm', 'ärm', 'plagg'] },
  { word: 'stövel', forbidden: ['sko', 'regn', 'gummi', 'fot', 'hög'] },
  { word: 'jacka', forbidden: ['kläder', 'ytterplagg', 'dragkedja', 'varm', 'höst'] },
  { word: 'kappa', forbidden: ['jacka', 'vinter', 'lång', 'kläder', 'ytterplagg'] },
  { word: 'bälte', forbidden: ['byxor', 'midja', 'spänne', 'läder', 'hålla'] },
  { word: 'slips', forbidden: ['skjorta', 'knyta', 'hals', 'kostym', 'mönstrad'] },
  { word: 'mössa', forbidden: ['huvud', 'vinter', 'varm', 'ull', 'kläder'] },
  { word: 'toffel', forbidden: ['sko', 'inne', 'hemma', 'fot', 'mjuk'] },
  { word: 'knapp', forbidden: ['skjorta', 'knapphål', 'sy', 'tröja', 'trycka'] },
  { word: 'bomull', forbidden: ['tyg', 'vit', 'plagg', 'växt', 'mjuk'] },
  { word: 'läder', forbidden: ['skinn', 'ko', 'sko', 'väska', 'brun'] },
  { word: 'matta', forbidden: ['golv', 'mjuk', 'damm', 'rum', 'ligga'] },
  { word: 'gardin', forbidden: ['fönster', 'tyg', 'hänga', 'dra', 'ljus'] },
  { word: 'trappa', forbidden: ['steg', 'upp', 'våning', 'räcke', 'gå'] },
  { word: 'badrum', forbidden: ['dusch', 'toalett', 'tvätta', 'rum', 'handfat'] },
  { word: 'staket', forbidden: ['trädgård', 'gräns', 'trä', 'hage', 'runt'] },
  { word: 'garage', forbidden: ['bil', 'hus', 'port', 'parkera', 'förvara'] },
  { word: 'stuga', forbidden: ['hus', 'sommar', 'skog', 'röd', 'liten'] },
  { word: 'lakan', forbidden: ['säng', 'sova', 'vit', 'bädda', 'tyg'] },
  { word: 'täcke', forbidden: ['säng', 'sova', 'varm', 'dun', 'bädd'] },
  { word: 'borste', forbidden: ['strå', 'borsta', 'hår', 'skaft', 'rengöra'] },
  { word: 'kvast', forbidden: ['sopa', 'golv', 'skaft', 'häxa', 'städa'] },
  { word: 'stege', forbidden: ['klättra', 'upp', 'pinne', 'hög', 'målare'] },
  { word: 'skruv', forbidden: ['mejsel', 'spik', 'gänga', 'trä', 'vrida'] },
  { word: 'flaska', forbidden: ['dricka', 'kork', 'glas', 'vatten', 'hälla'] },
  { word: 'kanna', forbidden: ['hälla', 'vatten', 'pip', 'handtag', 'kaffe'] },
  { word: 'bricka', forbidden: ['bära', 'servera', 'glas', 'platt', 'kaffe'] },
  { word: 'väska', forbidden: ['bära', 'axel', 'packa', 'handtag', 'resa'] },
  { word: 'sladd', forbidden: ['el', 'kontakt', 'lång', 'ström', 'koppla'] },
  { word: 'penna', forbidden: ['skriva', 'papper', 'bläck', 'rita', 'blyerts'] },
  { word: 'papper', forbidden: ['skriva', 'vit', 'ark', 'träd', 'riva'] },
  { word: 'kuvert', forbidden: ['brev', 'frimärke', 'posta', 'klistra', 'adress'] },
  { word: 'kavel', forbidden: ['deg', 'baka', 'rulla', 'trä', 'kaka'] },
  { word: 'termos', forbidden: ['varm', 'kaffe', 'hålla', 'utflykt', 'flaska'] },
  { word: 'dusch', forbidden: ['vatten', 'tvätta', 'badrum', 'strila', 'morgon'] },
  { word: 'badkar', forbidden: ['vatten', 'bada', 'badrum', 'ligga', 'tvätta'] },
  { word: 'fåtölj', forbidden: ['sitta', 'stol', 'mjuk', 'vardagsrum', 'vila'] },
  { word: 'galge', forbidden: ['hänga', 'kläder', 'garderob', 'skjorta', 'krok'] },
  { word: 'leksak', forbidden: ['barn', 'leka', 'docka', 'rolig', 'bil'] },
  { word: 'docka', forbidden: ['leksak', 'barn', 'flicka', 'leka', 'människa'] },
  { word: 'pussel', forbidden: ['bit', 'lägga', 'bild', 'spel', 'passa'] },
  { word: 'kvitto', forbidden: ['butik', 'betala', 'papper', 'köpa', 'pris'] },
  { word: 'sedel', forbidden: ['pengar', 'betala', 'papper', 'hundra', 'plånbok'] },
  { word: 'tvätt', forbidden: ['kläder', 'smutsig', 'maskin', 'ren', 'hänga'] },
  { word: 'kakao', forbidden: ['choklad', 'varm', 'dricka', 'pulver', 'brun'] },
  { word: 'godis', forbidden: ['söt', 'socker', 'lördag', 'barn', 'påse'] },
  { word: 'kniv', forbidden: ['skära', 'vass', 'bestick', 'gaffel', 'blad'] },
  { word: 'sked', forbidden: ['bestick', 'äta', 'soppa', 'röra', 'rund'] },
  { word: 'spis', forbidden: ['kök', 'laga', 'platta', 'ugn', 'varm'] },
  { word: 'stol', forbidden: ['sitta', 'möbel', 'ben', 'bord', 'rygg'] },
  { word: 'kylskåp', forbidden: ['kall', 'mat', 'kök', 'förvara', 'mjölk'] },
  { word: 'tallrik', forbidden: ['äta', 'mat', 'porslin', 'rund', 'disk'] },
  { word: 'potatis', forbidden: ['skala', 'koka', 'jord', 'grönsak', 'mos'] },
  { word: 'smörgås', forbidden: ['bröd', 'smör', 'ost', 'frukost', 'skiva'] },
  { word: 'pannkaka', forbidden: ['smet', 'steka', 'sylt', 'tunn', 'mjöl'] },
  { word: 'skjorta', forbidden: ['knapp', 'kläder', 'krage', 'kostym', 'ärm'] },
  { word: 'strumpa', forbidden: ['fot', 'sko', 'par', 'ull', 'kläder'] },
  { word: 'halsduk', forbidden: ['hals', 'vinter', 'varm', 'ull', 'linda'] },
  { word: 'klänning', forbidden: ['kvinna', 'kläder', 'plagg', 'fest', 'kjol'] },
  { word: 'hammare', forbidden: ['spik', 'slå', 'verktyg', 'skaft', 'snickare'] },
  { word: 'paraply', forbidden: ['regn', 'väta', 'fälla', 'handtag', 'skydda'] },
  { word: 'plånbok', forbidden: ['pengar', 'kort', 'ficka', 'sedel', 'läder'] },
  { word: 'buss', forbidden: ['hållplats', 'chaufför', 'passagerare', 'resa', 'biljett'] },
  { word: 'spårvagn', forbidden: ['räls', 'gata', 'göteborg', 'kollektiv', 'vagn'] },
  { word: 'bilist', forbidden: ['kör', 'bil', 'förare', 'väg', 'trafik'] },
  { word: 'brandbil', forbidden: ['eld', 'släcka', 'sirén', 'röd', 'utryckning'] },
  { word: 'lastbil', forbidden: ['gods', 'tung', 'släp', 'transport', 'chaufför'] },
  { word: 'traktor', forbidden: ['bonde', 'åker', 'jordbruk', 'hjul', 'plog'] },
  { word: 'flygplan', forbidden: ['luft', 'vinge', 'pilot', 'resa', 'flygplats'] },
  { word: 'färja', forbidden: ['båt', 'vatten', 'bil', 'överfart', 'hamn'] },
  { word: 'hamn', forbidden: ['båt', 'kaj', 'vatten', 'skepp', 'lasta'] },
  { word: 'kaj', forbidden: ['hamn', 'båt', 'vatten', 'kant', 'förtöja'] },
  { word: 'bro', forbidden: ['över', 'vatten', 'gå', 'förbinda', 'flod'] },
  { word: 'tunnel', forbidden: ['berg', 'under', 'genom', 'mörk', 'väg'] },
  { word: 'gata', forbidden: ['stad', 'hus', 'asfalt', 'gå', 'trottoar'] },
  { word: 'torg', forbidden: ['stad', 'öppen', 'marknad', 'plats', 'stånd'] },
  { word: 'trottoar', forbidden: ['gata', 'gå', 'kant', 'fotgängare', 'asfalt'] },
  { word: 'korsning', forbidden: ['gata', 'möts', 'trafikljus', 'väg', 'sväng'] },
  { word: 'rondell', forbidden: ['runt', 'bil', 'cirkel', 'trafik', 'köra'] },
  { word: 'parkering', forbidden: ['bil', 'ställa', 'plats', 'avgift', 'ruta'] },
  { word: 'verkstad', forbidden: ['laga', 'bil', 'mekaniker', 'reparera', 'verktyg'] },
  { word: 'fabrik', forbidden: ['tillverka', 'industri', 'maskin', 'arbetare', 'skorsten'] },
  { word: 'kontor', forbidden: ['jobb', 'skrivbord', 'dator', 'arbete', 'chef'] },
  { word: 'möte', forbidden: ['träffas', 'jobb', 'prata', 'kalender', 'rum'] },
  { word: 'chef', forbidden: ['bestämma', 'jobb', 'anställd', 'ledare', 'företag'] },
  { word: 'företag', forbidden: ['jobb', 'bolag', 'sälja', 'anställd', 'vinst'] },
  { word: 'lön', forbidden: ['pengar', 'jobb', 'månad', 'betala', 'konto'] },
  { word: 'bank', forbidden: ['pengar', 'konto', 'spara', 'lån', 'ränta'] },
  { word: 'affär', forbidden: ['handla', 'köpa', 'butik', 'kassa', 'vara'] },
  { word: 'butik', forbidden: ['handla', 'affär', 'köpa', 'kassa', 'skylt'] },
  { word: 'kassa', forbidden: ['betala', 'butik', 'kö', 'pengar', 'kvitto'] },
  { word: 'kundvagn', forbidden: ['butik', 'hjul', 'handla', 'skjuta', 'mat'] },
  { word: 'bageri', forbidden: ['bröd', 'baka', 'ugn', 'bulle', 'butik'] },
  { word: 'apotek', forbidden: ['medicin', 'recept', 'tablett', 'sjuk', 'butik'] },
  { word: 'kiosk', forbidden: ['godis', 'tidning', 'liten', 'lucka', 'sälja'] },
  { word: 'café', forbidden: ['kaffe', 'fika', 'bulle', 'sitta', 'servera'] },
  { word: 'krog', forbidden: ['mat', 'öl', 'restaurang', 'servera', 'kväll'] },
  { word: 'hotell', forbidden: ['sova', 'rum', 'resa', 'boka', 'gäst'] },
  { word: 'kyrka', forbidden: ['gud', 'präst', 'torn', 'gudstjänst', 'bön', 'altare', 'församling', 'moské', 'synagoga', 'tempel'] },
  { word: 'slott', forbidden: ['kung', 'stor', 'torn', 'gammal', 'byggnad'] },
  { word: 'torn', forbidden: ['hög', 'byggnad', 'upp', 'smal', 'klättra'] },
  { word: 'museum', forbidden: ['gammal', 'utställning', 'konst', 'besöka', 'föremål'] },
  { word: 'bibliotek', forbidden: ['bok', 'låna', 'läsa', 'tyst', 'hylla'] },
  { word: 'teater', forbidden: ['scen', 'skådespelare', 'pjäs', 'publik', 'föreställning'] },
  { word: 'biograf', forbidden: ['film', 'duk', 'popcorn', 'mörk', 'salong'] },
  { word: 'stadion', forbidden: ['fotboll', 'publik', 'match', 'läktare', 'arena'] },
  { word: 'arena', forbidden: ['match', 'publik', 'stor', 'konsert', 'läktare'] },
  { word: 'park', forbidden: ['grön', 'träd', 'gräs', 'bänk', 'promenad'] },
  { word: 'bänk', forbidden: ['sitta', 'park', 'trä', 'rygg', 'utomhus'] },
  { word: 'grind', forbidden: ['öppna', 'staket', 'in', 'trädgård', 'gångjärn'] },
  { word: 'hiss', forbidden: ['upp', 'våning', 'knapp', 'hus', 'åka'] },
  { word: 'våning', forbidden: ['hus', 'trappa', 'plan', 'bo', 'lägenhet'] },
  { word: 'källare', forbidden: ['under', 'hus', 'mörk', 'förvara', 'trappa'] },
  { word: 'vind', forbidden: ['hus', 'tak', 'överst', 'förvara', 'damm'] },
  { word: 'balkong', forbidden: ['lägenhet', 'ut', 'räcke', 'sitta', 'våning'] },
  { word: 'portik', forbidden: ['ingång', 'hus', 'valv', 'pelare', 'entré'] },
  { word: 'hus', forbidden: ['bo', 'tak', 'vägg', 'byggnad', 'dörr'] },
  { word: 'villa', forbidden: ['hus', 'bo', 'trädgård', 'familj', 'tomt'] },
  { word: 'lada', forbidden: ['bonde', 'hö', 'gård', 'röd', 'djur'] },
  { word: 'kvarn', forbidden: ['mala', 'mjöl', 'vinge', 'vind', 'säd'] },
  { word: 'fyr', forbidden: ['ljus', 'hav', 'skepp', 'torn', 'varna'] },
  { word: 'bunker', forbidden: ['skydd', 'betong', 'under', 'krig', 'gömma'] },
  { word: 'polis', forbidden: ['brott', 'tjuv', 'uniform', 'gripa', 'lag'] },
  { word: 'brandman', forbidden: ['eld', 'släcka', 'slang', 'rädda', 'stege'] },
  { word: 'läkare', forbidden: ['sjuk', 'vård', 'patient', 'medicin', 'vit'] },
  { word: 'lärare', forbidden: ['elev', 'undervisa', 'klass', 'prov', 'tavla'] },
  { word: 'bagare', forbidden: ['bröd', 'baka', 'ugn', 'deg', 'bulle'] },
  { word: 'snickare', forbidden: ['trä', 'hammare', 'bygga', 'spik', 'planka'] },
  { word: 'målare', forbidden: ['färg', 'pensel', 'vägg', 'stryka', 'hink'] },
  { word: 'bonde', forbidden: ['gård', 'åker', 'djur', 'skörd', 'traktor'] },
  { word: 'fiskare', forbidden: ['fisk', 'båt', 'nät', 'hav', 'fånga'] },
  { word: 'domare', forbidden: ['match', 'regel', 'vissla', 'rätt', 'beslut'] },
  { word: 'kontrakt', forbidden: ['avtal', 'skriva', 'under', 'papper', 'juridik'] },
  { word: 'skatt', forbidden: ['betala', 'stat', 'inkomst', 'deklaration', 'pengar'] },
  { word: 'gruva', forbidden: ['malm', 'under', 'berg', 'gräva', 'järn'] },
  { word: 'kran', forbidden: ['lyfta', 'tung', 'bygge', 'arm', 'hög'] },
  { word: 'dator', forbidden: ['skärm', 'tangentbord', 'internet', 'program', 'mus'] },
  { word: 'tumme', forbidden: ['finger', 'hand', 'kort', 'upp', 'tjock'] },
  { word: 'armbåge', forbidden: ['arm', 'led', 'böja', 'kropp', 'vika'] },
  { word: 'haka', forbidden: ['ansikte', 'mun', 'skägg', 'under', 'käke'] },
  { word: 'tunga', forbidden: ['mun', 'smaka', 'slicka', 'räcka', 'röd'] },
  { word: 'vrist', forbidden: ['fot', 'ben', 'led', 'stuka', 'smal'] },
  { word: 'lunga', forbidden: ['andas', 'luft', 'bröst', 'syre', 'organ'] },
  { word: 'njure', forbidden: ['organ', 'kropp', 'urin', 'böna', 'två'] },
  { word: 'revben', forbidden: ['bröst', 'skelett', 'ben', 'bur', 'kropp'] },
  { word: 'vad', forbidden: ['ben', 'muskel', 'bak', 'knä', 'springa'] },
  { word: 'puls', forbidden: ['hjärta', 'slag', 'blod', 'känna', 'handled'] },
  { word: 'fräkne', forbidden: ['hud', 'prick', 'sol', 'ansikte', 'brun'] },
  { word: 'rynka', forbidden: ['hud', 'gammal', 'ansikte', 'veck', 'ålder'] },
  { word: 'muskel', forbidden: ['stark', 'kropp', 'träna', 'arm', 'spänna'] },
  { word: 'smak', forbidden: ['tunga', 'mat', 'söt', 'sinne', 'sur'] },
  { word: 'doft', forbidden: ['lukta', 'näsa', 'parfym', 'god', 'blomma'] },
  { word: 'ljud', forbidden: ['höra', 'öra', 'hög', 'buller', 'eko'] },
  { word: 'eko', forbidden: ['ljud', 'berg', 'grotta', 'upprepa', 'studsa'] },
  { word: 'viskning', forbidden: ['tyst', 'prata', 'öra', 'låg', 'hemlighet'] },
  { word: 'skratt', forbidden: ['rolig', 'glad', 'skoja', 'mun', 'ljud'] },
  { word: 'gäspning', forbidden: ['trött', 'mun', 'sömn', 'smittsam', 'öppna'] },
  { word: 'nysning', forbidden: ['näsa', 'förkylning', 'prosit', 'allergi', 'ljud'] },
  { word: 'kittling', forbidden: ['skratta', 'fötter', 'känslig', 'finger', 'reta'] },
  { word: 'trumma', forbidden: ['slå', 'instrument', 'takt', 'band', 'pinne'] },
  { word: 'fiol', forbidden: ['stråke', 'instrument', 'sträng', 'orkester', 'spela'] },
  { word: 'flöjt', forbidden: ['blåsa', 'instrument', 'hål', 'ton', 'spela'] },
  { word: 'trumpet', forbidden: ['blåsa', 'mässing', 'instrument', 'jazz', 'ton'] },
  { word: 'sång', forbidden: ['sjunga', 'röst', 'text', 'musik', 'kör'] },
  { word: 'kör', forbidden: ['sjunga', 'grupp', 'röst', 'stämma', 'dirigent'] },
  { word: 'melodi', forbidden: ['låt', 'musik', 'ton', 'gnola', 'öra'] },
  { word: 'takt', forbidden: ['rytm', 'musik', 'räkna', 'trumma', 'dans'] },
  { word: 'not', forbidden: ['musik', 'papper', 'spela', 'läsa', 'ton'] },
  { word: 'skiva', forbidden: ['vinyl', 'musik', 'rund', 'spela', 'album'] },
  { word: 'hörlur', forbidden: ['öra', 'musik', 'lyssna', 'sladd', 'ljud'] },
  { word: 'dans', forbidden: ['röra', 'musik', 'golv', 'par', 'steg'] },
  { word: 'opera', forbidden: ['sjunga', 'scen', 'hus', 'musik', 'italiensk'] },
  { word: 'ridå', forbidden: ['scen', 'teater', 'tyg', 'gå', 'föreställning'] },
  { word: 'publik', forbidden: ['åskådare', 'titta', 'applåd', 'sitta', 'scen'] },
  { word: 'biljett', forbidden: ['köpa', 'bio', 'resa', 'papper', 'riva'] },
  { word: 'cirkus', forbidden: ['clown', 'tält', 'akrobat', 'djur', 'manege'] },
  { word: 'clown', forbidden: ['cirkus', 'näsa', 'rolig', 'peruk', 'smink'] },
  { word: 'dikt', forbidden: ['rim', 'poet', 'skriva', 'vers', 'text'] },
  { word: 'roman', forbidden: ['bok', 'läsa', 'författare', 'berättelse', 'sida'] },
  { word: 'pensel', forbidden: ['måla', 'färg', 'konst', 'hår', 'skaft'] },
  { word: 'färg', forbidden: ['måla', 'röd', 'blå', 'burk', 'penna'] },
  { word: 'lera', forbidden: ['forma', 'krukmakare', 'jord', 'bränna', 'kruka'] },
  { word: 'staty', forbidden: ['sten', 'konst', 'torg', 'stå', 'brons'] },
  { word: 'målning', forbidden: ['konst', 'duk', 'färg', 'vägg', 'konstnär'] },
  { word: 'saga', forbidden: ['berättelse', 'barn', 'bok', 'prins', 'gång'] },
  { word: 'mål', forbidden: ['fotboll', 'poäng', 'nät', 'skjuta', 'vinna'] },
  { word: 'lag', forbidden: ['spelare', 'match', 'tillsammans', 'tröja', 'sport'] },
  { word: 'match', forbidden: ['spela', 'lag', 'vinna', 'sport', 'publik'] },
  { word: 'skida', forbidden: ['snö', 'backe', 'åka', 'stav', 'vinter'] },
  { word: 'skridsko', forbidden: ['is', 'åka', 'vinter', 'skär', 'hockey'] },
  { word: 'simning', forbidden: ['vatten', 'bassäng', 'bad', 'crawl', 'sport'] },
  { word: 'racket', forbidden: ['tennis', 'slå', 'boll', 'badminton', 'sträng'] },
  { word: 'klubba', forbidden: ['hockey', 'golf', 'slå', 'puck', 'skaft'] },
  { word: 'puck', forbidden: ['hockey', 'is', 'gummi', 'svart', 'rund'] },
  { word: 'medalj', forbidden: ['guld', 'vinna', 'hänga', 'tävling', 'hals'] },
  { word: 'pokal', forbidden: ['vinna', 'silver', 'guld', 'pris', 'tävling', 'hylla'] },
  { word: 'tävling', forbidden: ['vinna', 'först', 'delta', 'pris', 'sport'] },
  { word: 'hopp', forbidden: ['studsa', 'höjd', 'ben', 'luft', 'längd'] },
  { word: 'löpning', forbidden: ['springa', 'ben', 'spår', 'snabb', 'motion'] },
  { word: 'tärning', forbidden: ['kasta', 'sex', 'spel', 'prick', 'kub'] },
  { word: 'gunga', forbidden: ['lekplats', 'fram', 'sitta', 'rep', 'barn'] },
  { word: 'drake', forbidden: ['vind', 'flyga', 'snöre', 'himmel', 'eld'] },
  { word: 'ballong', forbidden: ['luft', 'blåsa', 'spricka', 'fest', 'gummi'] },
  { word: 'nalle', forbidden: ['björn', 'mjuk', 'leksak', 'barn', 'gosa'] },
  { word: 'kortlek', forbidden: ['spela', 'hjärter', 'blanda', 'spader', 'femtiotvå'] },
  { word: 'hobby', forbidden: ['fritid', 'intresse', 'syssla', 'roligt', 'utöva'] },
  { word: 'resa', forbidden: ['semester', 'flyg', 'väska', 'åka', 'utomlands'] },
  { word: 'koffert', forbidden: ['väska', 'resa', 'packa', 'stor', 'lock'] },
  { word: 'timme', forbidden: ['minut', 'klocka', 'sextio', 'tid', 'dygn'] },
  { word: 'vecka', forbidden: ['sju', 'dag', 'måndag', 'helg', 'kalender'] },
  { word: 'månad', forbidden: ['år', 'trettio', 'dag', 'kalender', 'januari'] },
  { word: 'skymning', forbidden: ['kväll', 'mörk', 'sol', 'ner', 'dag'] },
  { word: 'kalender', forbidden: ['dag', 'datum', 'år', 'vägg', 'månad'] },
  { word: 'jul', forbidden: ['gran', 'tomte', 'klapp', 'december', 'skinka'] },
  { word: 'påsk', forbidden: ['ägg', 'kyckling', 'häxa', 'gul', 'ris'] },
  { word: 'kalas', forbidden: ['fest', 'tårta', 'födelsedag', 'gäst', 'barn'] },
  { word: 'tårta', forbidden: ['ljus', 'födelsedag', 'grädde', 'söt', 'baka'] },
  { word: 'present', forbidden: ['paket', 'ge', 'födelsedag', 'snöre', 'öppna'] },
  { word: 'krans', forbidden: ['blomma', 'midsommar', 'huvud', 'rund', 'bind'] },

  // --- verb ---
  { word: 'viska', forbidden: ['tyst', 'prata', 'öra', 'hemlighet', 'låg'], class: 'verb' },
  { word: 'gäspa', forbidden: ['trött', 'mun', 'sömn', 'öppna', 'morgon'], class: 'verb' },
  { word: 'krypa', forbidden: ['golv', 'långsam', 'mage', 'insekt', 'bebis'], class: 'verb' },
  { word: 'simma', forbidden: ['vatten', 'bassäng', 'hav', 'flyta', 'bad'], class: 'verb' },
  { word: 'vissla', forbidden: ['mun', 'melodi', 'ton', 'ljud', 'låt'], class: 'verb' },
  { word: 'snarka', forbidden: ['sova', 'ljud', 'natt', 'näsa', 'säng'], class: 'verb' },
  { word: 'blinka', forbidden: ['öga', 'ljus', 'snabb', 'signal', 'lampa'], class: 'verb' },
  { word: 'frysa', forbidden: ['kall', 'is', 'kyla', 'vinter', 'grader'], class: 'verb' },
  { word: 'smälta', forbidden: ['is', 'värme', 'flytande', 'snö', 'choklad'], class: 'verb' },
  { word: 'knacka', forbidden: ['dörr', 'ljud', 'slå', 'hand', 'hammare'], class: 'verb' },
  { word: 'gräva', forbidden: ['jord', 'spade', 'hål', 'mark', 'skatt'], class: 'verb' },
  { word: 'vandra', forbidden: ['gå', 'skog', 'led', 'fötter', 'tur'], class: 'verb' },
  { word: 'sjunga', forbidden: ['röst', 'sång', 'ton', 'kör', 'musik'], class: 'verb' },
  { word: 'dansa', forbidden: ['musik', 'rörelse', 'golv', 'steg', 'takt'], class: 'verb' },
  { word: 'måla', forbidden: ['färg', 'pensel', 'tavla', 'konst', 'vägg'], class: 'verb' },
  { word: 'bygga', forbidden: ['hus', 'konstruera', 'tegel', 'snickare', 'grund'], class: 'verb' },
  { word: 'städa', forbidden: ['ren', 'damm', 'sopa', 'hem', 'ordning'], class: 'verb' },
  { word: 'vattna', forbidden: ['växt', 'kanna', 'torr', 'blomma', 'jord'], class: 'verb' },
  { word: 'drömma', forbidden: ['sömn', 'natt', 'fantasi', 'mardröm', 'önska'], class: 'verb' },
  { word: 'lyssna', forbidden: ['öra', 'ljud', 'höra', 'tyst', 'uppmärksam'], class: 'verb' },
  { word: 'glömma', forbidden: ['minne', 'komma', 'tappa', 'hjärna', 'påminna'], class: 'verb' },
  { word: 'längta', forbidden: ['sakna', 'vilja', 'önska', 'vänta', 'hem'], class: 'verb' },
  { word: 'hoppa', forbidden: ['studsa', 'upp', 'ben', 'hage', 'luft'], class: 'verb' },
  { word: 'kasta', forbidden: ['boll', 'hand', 'luft', 'slänga', 'mål'], class: 'verb' },
  { word: 'fånga', forbidden: ['boll', 'hand', 'gripa', 'fisk', 'nät'], class: 'verb' },
  { word: 'somna', forbidden: ['sömn', 'säng', 'natt', 'trött', 'vakna'], class: 'verb' },
  { word: 'tvätta', forbidden: ['ren', 'vatten', 'tvål', 'kläder', 'maskin'], class: 'verb' },
  { word: 'steka', forbidden: ['panna', 'olja', 'spis', 'mat', 'brun'], class: 'verb' },
  { word: 'borsta', forbidden: ['tand', 'hår', 'borste', 'ren', 'päls'], class: 'verb' },
  { word: 'krama', forbidden: ['armar', 'famn', 'kärlek', 'tryck', 'hälsa'], class: 'verb' },
  { word: 'vinka', forbidden: ['hand', 'hej', 'adjö', 'arm', 'hälsa'], class: 'verb' },
  { word: 'halka', forbidden: ['is', 'glatt', 'falla', 'snö', 'underlag'], class: 'verb' },
  { word: 'skrika', forbidden: ['hög', 'röst', 'ljud', 'rädd', 'öra'], class: 'verb' },
  { word: 'gnida', forbidden: ['fram', 'tillbaka', 'yta', 'hand', 'tryck'], class: 'verb' },
  { word: 'smyga', forbidden: ['tyst', 'långsam', 'oupptäckt', 'tå', 'gömma'], class: 'verb' },
  { word: 'klänga', forbidden: ['hålla', 'upp', 'gren', 'fast', 'apa'], class: 'verb' },
  { word: 'plocka', forbidden: ['hand', 'bär', 'svamp', 'korg', 'skog'], class: 'verb' },
  { word: 'skölja', forbidden: ['vatten', 'ren', 'kran', 'disk', 'hälla'], class: 'verb' },
  { word: 'vrida', forbidden: ['runt', 'varv', 'hand', 'ratt', 'vrid'], class: 'verb' },

  // --- adjektiv ---
  { word: 'modig', forbidden: ['mod', 'rädd', 'hjälte', 'våga', 'tapper'], class: 'adjektiv' },
  { word: 'envis', forbidden: ['vilja', 'bestämd', 'ge', 'sta', 'envishet'], class: 'adjektiv' },
  { word: 'girig', forbidden: ['pengar', 'snål', 'samla', 'girighet', 'begär'], class: 'adjektiv' },
  { word: 'blyg', forbidden: ['tyst', 'folk', 'rodna', 'social', 'tillbakadragen'], class: 'adjektiv' },
  { word: 'pigg', forbidden: ['trött', 'energi', 'vaken', 'frisk', 'morgon'], class: 'adjektiv' },
  { word: 'mätt', forbidden: ['hungrig', 'äta', 'mage', 'mat', 'nöjd'], class: 'adjektiv' },
  { word: 'brant', forbidden: ['backe', 'lutning', 'uppför', 'berg', 'sluttning'], class: 'adjektiv' },
  { word: 'smal', forbidden: ['tunn', 'bred', 'mager', 'midja', 'bredd'], class: 'adjektiv' },
  { word: 'tjock', forbidden: ['tunn', 'bred', 'fet', 'lager', 'tjocklek'], class: 'adjektiv' },
  { word: 'mjuk', forbidden: ['hård', 'kudde', 'ull', 'beröring', 'känsla'], class: 'adjektiv' },
  { word: 'sträv', forbidden: ['slät', 'yta', 'grov', 'sandpapper', 'känna'], class: 'adjektiv' },
  { word: 'besk', forbidden: ['smak', 'bitter', 'mandel', 'kaffe', 'tunga'], class: 'adjektiv' },
  { word: 'kylig', forbidden: ['kall', 'temperatur', 'luft', 'sval', 'frost'], class: 'adjektiv' },
  { word: 'ivrig', forbidden: ['entusiasm', 'otålig', 'vänta', 'spänd', 'glad'], class: 'adjektiv' },
  { word: 'vaken', forbidden: ['sova', 'öppen', 'natt', 'medveten', 'morgon'], class: 'adjektiv' },
  { word: 'klok', forbidden: ['vis', 'smart', 'dum', 'kunskap', 'råd'], class: 'adjektiv' },
  { word: 'ärlig', forbidden: ['sanning', 'ljuga', 'uppriktig', 'lita', 'rak'], class: 'adjektiv' },
  { word: 'ledsen', forbidden: ['gråta', 'tår', 'sorg', 'glad', 'humör'], class: 'adjektiv' },
  { word: 'lugn', forbidden: ['stress', 'stilla', 'fridfull', 'andas', 'ro'], class: 'adjektiv' },
  { word: 'snabb', forbidden: ['fort', 'långsam', 'hastighet', 'springa', 'kvick'], class: 'adjektiv' },
  { word: 'tung', forbidden: ['vikt', 'lätt', 'bära', 'kilo', 'lyfta'], class: 'adjektiv' },
  { word: 'vass', forbidden: ['kniv', 'egg', 'skära', 'spets', 'tagg'], class: 'adjektiv' },
  { word: 'trång', forbidden: ['smal', 'plats', 'klämma', 'bred', 'utrymme'], class: 'adjektiv' },
  { word: 'rymlig', forbidden: ['plats', 'stor', 'utrymme', 'trång', 'öppen'], class: 'adjektiv' },
  { word: 'ihålig', forbidden: ['tom', 'inuti', 'rör', 'ek', 'fylld'], class: 'adjektiv' },
  { word: 'dyster', forbidden: ['mörk', 'glad', 'stämning', 'grå', 'hopplös'], class: 'adjektiv' },
  { word: 'slö', forbidden: ['vass', 'trött', 'lat', 'energi', 'matt'], class: 'adjektiv' },
  { word: 'fuktig', forbidden: ['blöt', 'torr', 'vatten', 'luft', 'klam'], class: 'adjektiv' },
  { word: 'bräcklig', forbidden: ['ömtålig', 'gå', 'glas', 'stark', 'försiktig'], class: 'adjektiv' },
  { word: 'luddig', forbidden: ['hår', 'yta', 'oskarp', 'ull', 'mjuk'], class: 'adjektiv' },
  { word: 'skarp', forbidden: ['kniv', 'tydlig', 'suddig', 'egg', 'blick'], class: 'adjektiv' },
  { word: 'stormig', forbidden: ['vind', 'väder', 'hav', 'lugn', 'blåst'], class: 'adjektiv' },
  { word: 'kryddig', forbidden: ['smak', 'stark', 'peppar', 'mat', 'chili'], class: 'adjektiv' },
  { word: 'nyfiken', forbidden: ['undra', 'fråga', 'veta', 'katt', 'intresse'], class: 'adjektiv' },
  { word: 'tacksam', forbidden: ['tack', 'glad', 'uppskatta', 'gåva', 'skuld'], class: 'adjektiv' },
  { word: 'bekväm', forbidden: ['skön', 'stol', 'mjuk', 'obekväm', 'vila'], class: 'adjektiv' },
  { word: 'hemlig', forbidden: ['dold', 'viska', 'avslöja', 'gömma', 'tyst'], class: 'adjektiv' },
];

export function wordByIndex(idx) {
  const entry = WORDS[idx];
  if (!entry) return null;
  return {
    index: idx,
    word: entry.word,
    forbidden: entry.forbidden,
    letterCount: letterCount(entry.word),
    // Defaulted here rather than at each use, so the player, the prompt and
    // the tests can never disagree about what an unlabelled entry is. Only
    // verbs and adjectives are written down in the bank; everything else is a
    // noun, and saying so out loud costs nothing.
    class: entry.class ?? 'substantiv',
    // Optional, and absent for every word that hasn't been probed yet —
    // clueLimitFor() falls back to the global default. Carried through here so
    // callers never have to reach back into WORDS for it.
    limit: entry.limit,
  };
}

/**
 * Deterministic daily rotation: same date → same word for everyone.
 *
 * The schedule is read from a committed array rather than computed from the
 * bank size. Computing it — `(dayNumber * STRIDE) % WORDS.length` — made every
 * date depend on how many words exist, so adding words silently rewrote the
 * calendar, today included, while people were mid-play. See server/rotation.js.
 */
export function wordForDate(dateStr) {
  const pos = dayNumber(dateStr) - ROTATION_EPOCH;
  const n = ROTATION.length;
  return wordByIndex(ROTATION[((pos % n) + n) % n]);
}

/**
 * A random word for practice mode, never today's — practising on the live word
 * would be a free way around the daily attempt limit.
 */
export function randomWord(excludeIndex) {
  if (WORDS.length < 2) return wordByIndex(0);
  let idx;
  do {
    idx = Math.floor(Math.random() * WORDS.length);
  } while (idx === excludeIndex);
  return wordByIndex(idx);
}
